### GET users
GET http://localhost:5059/auth/me
Content-Type: application/json

### POST register
POST http://localhost:5059/auth/register
Content-Type: application/json

{
  "email": "test@example.com",
  "name": "test",
  "password": "password123",
  "confirmPassword": "password123"
}

### POST login
POST http://localhost:5059/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123"
}

### POST logout
POST http://localhost:5059/auth/logout
Content-Type: application/json



### POST create quest
POST http://localhost:5059/quest/create
Content-Type: application/json

{
  "Category": "test",
  "Title": "test quest",
  "TotalTimeMs": 10000,
  "IntervalCount": 5,
  "Breaks":{
    "Short": 10000,
    "Long": 5000
  }
}


### GET current quest
GET http://localhost:5059/quest/current
Content-Type: application/json